version: '3'
services:  
    grafana:
        image: "grafana/grafana-custom"
        ports:
            - "3000:3000"
        networks:
            - cluster
    flask:
        image: "flask-test:2.7"
        ports:
            - "5000:5000"
        networks:
            - cluster
        volumes:
            - ./prometheus:/etc/prometheus
            - prometheus-data:/prometheus
    prometheus:
        image: "quay.io/prometheus/prometheus:v2.25.2"
        ports:
            - "9090:9090"
        networks:
            - cluster
        volumes:
            - ./prometheus:/etc/prometheus
            - prometheus-data:/prometheus
        command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
networks:
    cluster:
volumes:
    prometheus-data: