global:
  scrape_interval: 60s
  scrape_timeout: 10s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

    # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
    - "alert_rules.yml"

scrape_configs:
  - job_name: mtx-exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'custom:5000'
  # - job_name: pricing-status
  #   metrics_path: /api/collectTime
  #   static_configs:
  #     - targets:
  #         - 'custom:5000'
  